# 1.) Which products and categories generate the highest revenue? (Order Items & Product Table)
SELECT 
	p.product_id, 
    -- Use English translation for readability in reports
	ct.product_category_name_english AS product_category_name, 
	SUM(oi.price) as total_product_revenue, 
    -- Identifying volume per product to distinguish between "high price" vs "high frequency" items
	COUNT(DISTINCT oi.order_id)
FROM order_items oi
LEFT JOIN products p on oi.product_id = p.product_id
-- Mapping Portuguese categories to English via translation lookup table
LEFT JOIN category_translations ct ON p.product_category_name = ct.product_category_name
WHERE product_category_name_english IS NOT NULL
GROUP BY p.product_id , ct.product_category_name_english
ORDER BY total_product_revenue DESC
LIMIT 10;

-- Top 10 categories by revenue, including shipping (freight) breakdown
SELECT 
	ct.product_category_name_english AS product_category_name, 
	SUM(oi.price) as total_product_revenue, 
	SUM(oi.freight_value) as total_shipping_revenue,
    -- Combined revenue shows the total cash flow generated by the category
	SUM(oi.price + oi.freight_value) as total_combined_revenue
FROM order_items oi
LEFT JOIN products p on oi.product_id = p.product_id
LEFT JOIN category_translations ct ON p.product_category_name = ct.product_category_name
WHERE product_category_name_english IS NOT NULL
GROUP BY ct.product_category_name_english
ORDER BY total_product_revenue DESC
LIMIT 10;

# 2.) Is revenue concentrated among a small number of products or brands? (Pareto Analysis)

-- Step 1: Aggregate revenue by category
WITH CategoryRevenue AS (
    SELECT 
        ct.product_category_name_english AS product_category_name,
        SUM(oi.price) AS category_revenue
    FROM order_items oi
    JOIN products p ON oi.product_id = p.product_id
    LEFT JOIN category_translations ct
    ON p.product_category_name = ct.product_category_name
	WHERE product_category_name_english IS NOT NULL
    GROUP BY ct.product_category_name_english
),

-- Step 2: Rank categories and calculate running totals for concentration analysis
RankedCategories AS (
	SELECT 
		product_category_name,
        category_revenue,
        RANK() OVER (ORDER BY category_revenue DESC) as category_rank,
        -- Running total allows us to calculate the cumulative impact of top categories
        SUM(category_revenue) OVER (ORDER BY category_revenue DESC) as running_total,
        -- Total revenue across all categories for percentage calculation
        SUM(category_revenue) OVER () as total_revenue
	FROM CategoryRevenue
)
-- Step 3: Final output showing cumulative percentage (e.g., do top 10 categories make up 80% of revenue?)
SELECT 
    product_category_name,
    category_revenue,
    category_rank,
    ROUND((running_total / total_revenue) * 100, 2) as cumulative_percentage
FROM RankedCategories
ORDER BY category_rank ASC;
